version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Berlin"
    assignees:
      - 0xflotus
    open-pull-requests-limit: 5
    groups:
      patch-updates:
        update-types:
          - "patch"
      dev-dependencies:
        dependency-type: development
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - 0xflotus
