language: node_js
node_js:
  - 15
  - 14
  - 13
  - 12
  - 11
  - 10
os:
  - linux
  - osx
  - freebsd
  - windows
jobs:
  allow_failures:
    os: 
      - windows
      - freebsd
    node_js:
      - 11
arch:
  - amd64
  - arm64
notifications:
  email: true
