name: Create Diagram

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    name: Create Diagram
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: ".github,.circleci"
