name: Testing

on:
  push:
    branches:
      - main
    paths:
      - "**/*.mjs"
      - "**/*.js"
      - ".github/workflows/*.yml"
      - "package.json"
  pull_request:
    branches:
      - main
    paths:
      - "**/*.mjs"
      - "**/*.js"
      - ".github/workflows/*.yml"
      - "package.json"

concurrency:
  group: testing-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-slim
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm run lint
  build:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        version: [20, 22, 24]
        os: [ubuntu-latest, ubuntu-22.04]
    name: Testing
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Testing with Node ${{ matrix.version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
          cache: npm
      - run: npm ci
      - run: npm test
