name: Testing

on:
  push:
    branches:
      - main
    paths:
      - '**/*.mjs'
      - '**/*.js'
      - '.github/workflows/*.yml'
      - 'package.json'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.mjs'
      - '**/*.js'
      - '.github/workflows/*.yml'
      - 'package.json'

concurrency:
  group: testing-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  size:
    name: Check Size
    runs-on: ubuntu-slim
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npx size-limit
  lint:
    name: Lint Code Base
    runs-on: ubuntu-slim
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm run lint
  test:
    name: Testing
    needs: lint, size
    strategy:
      fail-fast: false
      matrix:
        version: [22, 24]
        os: [ubuntu-latest, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Testing with Node ${{ matrix.version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.version }}
          cache: npm
      - run: npm ci
      - run: npm run coverage
