name: Testing

on:
  push:
    branches: 
      - main
    paths:
      - "**.js"
  pull_request:
    branches: 
      - main

jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Testing with Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install jest
      - run: npm test
