name: Testing

on:
  push:
    branches:
      - main
    paths:
      - "**.js"
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        version: [18, 20, 22]
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Testing with Node 20
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - run: npm install jest
      - run: npm test
