name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        version: [18, 20, 22]
        os: [ubuntu-latest, ubuntu-24.04, ubuntu-22.04]
    name: Testing
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Testing with Node ${{ matrix.version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - run: npm install jest
      - run: npm test
